language: generic 

sudo: required

services:
    - docker

before_install:
    - docker build -t dlameyer/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dlameyer/docker-react npm run test
